/**
 * Created by cuss on 2017/5/23.
 */


export default{
  GET_USER:'GET_USER',
  GET_IS_TAKE_PHOTO:'GET_IS_TAKE_PHOTO',
  GET_USER_PHOTO_INFO:'GET_USER_PHOTO_INFO',
  SET_WEIXIN_READY:'SET_WEIXIN_READY',
  FETCH_USER_INFO:'FETCH_USER_INFO',
  FETCH_IS_TAKE_PHOTO:'FETCH_IS_TAKE_PHOTO',
  POST_USER_PHOTO:'POST_USER_PHOTO'
}
